baseURL = "https://sriramviswanathan.com/"
languageCode = "en"
theme = "sriram"
title = "Sriram Viswanathan"

[pagination]
pagerSize = 8

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "pastie"
lineNos = false
noClasses = false

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "posts"
name = "Writing"
url = "/posts/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Topics"
url = "/tags/"
weight = 3

[params]
abbrDateFmt = "Jan 2"
dateFmt = "2006-01-02"
author = "Sriram Viswanathan"
subtitle = "Poetry, Software, Privacy & Thoughts"
description = "A personal space for poetry, tech musings, and reflections."

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/sriramvish/"

[[params.social]]
name = "mastodon"
url = "https://hostux.social/@sriramv"

[[params.social]]
name = "soundcloud"
url = "https://soundcloud.com/inthemidstofitall"

[[params.social]]
name = "github"
url = "https://github.com/FrailWords"

[[params.social]]
name = "stackoverflow"
url = "https://stackoverflow.com/users/1216748/frailwords"
